[package]
name = "onvif-test-02"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytes = "1.1"
opencv = "0.84.5"
reqwest = "0.11"
url = "2.4"
xml-rs = "0.8"
image = "0.24.6"
ndarray = "0.15.6"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.ort]
version = "1.15.2"
